# --- TELEGRAM YAPILANDIRMASI ---
# Bu bilgileri BotFather ve UserInfoBot üzerinden alıp buraya yazın
TELEGRAM = {
    "TOKEN": "8255121421:AAG1biq7jrgLFAbWmzOFs6D4wsPzoDUjYeM", 
    "CHAT_ID": "-1003728280766"
}

# --- ANALİZ KRİTERLERİ (Orijinal Değerleriniz) ---
KRITERLER = {
    "RSI_ALT_ESIK": 35,
    "RSI_UST_ESIK": 70,
    "MIN_MA_GUN": 200,
    "PUAN_ESIGI": 20,
    "TARAMA_ARALIGI": 1800,
    "STOP_KAYIP_ORANI": 0.05
}

# --- BIST SEMBOL LİSTESİ ---
# Hocam listeyi kısa tutuyorum, çalışırsa diğerlerini eklersiniz.
HISSE_LISTESI = [
   "A1CAP", "ACSEL", "ADEL", "ADESE", "ADGYO", "AEFES", "AFYON", "AGESA", "AGHOL", "AGROT",
    "AGYO", "AHGAZ", "AHSGY", "AKBNK", "AKCNS", "AKENR", "AKFGY", "AKFYE", "AKGRT", "AKMGY",
    "AKSA", "AKSEN", "AKYHO", "ALARK", "ALBRK", "ALCAR", "ALCTL", "ALFAS", "ALKIM", "ALKA",
    "ANELE", "ANGEN", "ARASE", "ARCLK", "ARDYZ", "ARENA", "ARSAN", "ARTMS", "ASELS",
    "ASGYO", "ASTOR", "ASUZU", "ATAGY", "ATAKP", "ATATP", "ATEKS", "ATLAS", "ATSYH", "AVGYO",
    "AVHOL", "AVOD", "AVTUR", "AYCES", "AYDEM", "AYEN", "AYES", "AYGAZ", "AZTEK", "BAGFS",
    "BAKAB", "BALAT", "BNTAS", "BANVT", "BARMA", "BASGZ", "BASCM", "BTCIM", "BSOKE", "BAYRK",
    "BERA", "BRKSN", "BJKAS", "BEYAZ", "BLCYT", "BIMAS", "BIOEN", "BRKVY", "BRKO", "BRLSM",
    "BRMEN", "BIZIM", "BMSTL", "BMSCH", "BOBET", "BRSAN", "BRYAT", "BFREN", "BOSSA", "BRISA",
    "BURCE", "BURVA", "BUCIM", "BVSAN", "BIENY", "BIGCH", "CRFSA", "CASA", "CEOEM", "CCOLA",
    "CONSE", "COSMO", "CRDFA", "CANTE", "CLEBI", "CELHA", "CEMAS", "CEMTS", "CMBTN", "CMENT",
    "CIMSA", "CUSAN", "CWENE", "CVKMD", "DAGI", "DAPGM", "DARDL", "DGATE", "DMSAS",
    "DENGE", "DZGYO", "DERIM", "DERHL", "DESA", "DESPC", "DEVA", "DNISI", "DIRIT", "DITAS",
    "DOHOL", "DGNMO", "DOGUB", "DGGYO", "DOAS", "DOKTA", "DURDO", "DYOBY", "EDATA",
    "ECZYT", "EDIP", "EGEEN", "EGGUB", "EGPRO", "EGSER", "EPLAS", "ECILC", "EKIZ", "ELITE",
    "EMKEL", "EMNIS", "EKGYO", "ENJSA", "ENKAI", "ENSRI", "ERBOS", "ERCB", "EREGL",
    "KIMMR", "ERSU", "ESCAR", "ESCOM", "ESEN", "ETILR", "EUKYO", "EUYO", "ETYAT", "EUHOL",
    "TEZOL", "EUREN", "EYGYO", "EUPWR", "EKSUN", "FADE", "FMIZP", "FENER", "FLAP", "FONET",
    "FROTO", "FORMT", "FRIGO", "GWIND", "GSRAY", "GARFA", "GRNYO", "GEDIK", "GEDZA", "GLCVY",
    "GENIL", "GENTS", "GEREL", "GZNMI", "GMTAS", "GESAN", "GLYHO", "GOODY", "GOLTS", "GOZDE",
    "GSDDE", "GSDHO", "GUBRF", "GLRYH", "GRSEL", "GOKNR", "SAHOL", "HLGYO", "HATEK", "HDFGS",
    "HEDEF", "HEKTS", "HKTM", "HTTBT", "HUBVC", "HUNER", "HURGZ", "ICBCT", "INVEO", "INVES",
    "ISKPL", "IEYHO", "IDEAS", "IDGYO", "IHEVA", "IHLGM", "IHGZT", "IHAAS", "IHLAS", "IHYAY",
    "IMASM", "INDES", "INFO", "INTEM", "ISDMR", "ISFIN", "ISGYO", "ISGSY", "ISMEN",
    "ISYAT", "ISSEN", "IZINV", "IZMDC", "IZFAS", "JANTS", "KFEIN", "KLKIM", "KAPLM",
    "KAREL", "KARSN", "KRTEK", "KARTN", "KATMR", "KENT", "KRVGD", "KERVN",
    "KZBGY", "KLGYO", "KLRHO", "KMPUR", "KLMSN", "KCAER", "KCHOL", "KLSYN", "KNFRT", "KONTR",
    "KONYA", "KONKA", "KGYO", "KORDS", "KRPLS", "KRGYO", "KRSTL", "KRONT",
    "KSTUR", "KUVVA", "KUYAS", "KUTPO", "KTSKR", "KAYSE", "KOPOL", "LIDER", "LIDFA", "LINK",
    "LOGO", "LKMNH", "LUKSK", "MACKO", "MAKIM", "MAKTK", "MANAS", "MAGEN", "MARKA", "MAALT",
    "MRSHL", "MRGYO", "MARTI", "MTRKS", "MAVI", "MZHLD", "MEDTR", "MEGAP", "MNDRS", "MEPET",
    "MERCN", "MERIT", "MERKO", "METRO", "MTRYO", "MIATK", "MGROS", "MSGYO",
    "MPARK", "MOBTL", "MNDTR", "NATEN", "NTGAZ", "NTHOL", "NETAS", "NIBAS", "NUHCM", "NUGYO",
    "OBASE", "ODAS", "ONCSM", "ORCAY", "ORGE", "ORMA", "OSMEN", "OSTIM", "OTKAR", "OYAKC",
    "OYYAT", "OYAYO", "OYLUM", "OZKGY", "OZGYO", "OZRDN", "OZSUB", "PAMEL", "PNLSN", "PAGYO",
    "PAPIL", "PRDGS", "PRKME", "PARSN", "PSGYO", "PCILT", "PGSUS", "PEKGY", "PENGD", "PENTA",
    "PSDTC", "PETKM", "PKENT", "PETUN", "PINSU", "PNSUT", "PKART", "POLHO", "POLTK",
    "PRZMA", "QUAGR", "RNPOL", "RALYH", "RAYSG", "RYGYO", "RYSAS", "RHEAG", "RODRG", "RTALB",
    "RUBNS", "SAFKR", "SANEL", "SNICA", "SANFM", "SANKO", "SAMAT", "SASA",
    "SAYAS", "SDTTR", "SEKUR", "SELEC", "SELVA", "SRVGY", "SEYKM", "SILVR", "SNGYO",
    "SMRTG", "SMART", "SODSN", "SOKE", "SKTAS", "SONME", "SNPAM", "SUMAS", "SUNTK", "SUWEN",
    "SEKFK", "SEGYO", "SKBNK", "SOKM", "TNZTP", "TATGD", "TAVHL", "TEKTU", "TKFEN", "TKNSA",
    "TMPOL", "TERA", "TETMT", "TGSAS", "TOASO", "TRGYO", "TSPOR", "TDGYO", "TSGYO", "TUCLK",
    "TUKAS", "TRCAS", "TUREX", "TRILC", "TCELL", "TMSN", "TUPRS", "THYAO", "PRKAB", "TTKOM",
    "TTRAK", "TBORG", "TURGG", "TURSG", "UFUK", "ULAS", "ULUFA", "ULUSE", "USAK",
    "UZERB", "ULKER", "UNLU", "VAKFN", "VKGYO", "VKFYO", "VAKKO", "VANGD", "VBTYZ", "VERUS",
    "VERTU", "VESBE", "VESTL", "VKING", "YAPRK", "YATAS", "YYLGD", "YAYLA", "YGGYO", "YEOTK",
    "YGYO", "YYAPI", "YESIL", "YBTAS", "YONGA", "YKSLN", "YUNSA", "ZEDUR", "ZRGYO", "ZOREN"


]
